## 引用函式庫 ##

In [1]:
import numpy as np
import pandas as pd

## 資料前處理

In [2]:
input_df = pd.read_csv('bank-additional.csv', header=0, sep=';')

In [3]:
input_df

age          job  marital          education default  housing     loan  \
0      30  blue-collar  married           basic.9y      no      yes       no   
1      39     services   single        high.school      no       no       no   
2      25     services  married        high.school      no      yes       no   
3      38     services  married           basic.9y      no  unknown  unknown   
4      47       admin.  married  university.degree      no      yes       no   
...   ...          ...      ...                ...     ...      ...      ...   
4114   30       admin.  married           basic.6y      no      yes      yes   
4115   39       admin.  married        high.school      no      yes       no   
4116   27      student   single        high.school      no       no       no   
4117   58       admin.  married        high.school      no       no       no   
4118   34   management   single        high.school      no      yes       no   

        contact month day_of_week  ...  campaign  pdays  previous  \
0      cellular   may         fri  ...         2    999         0   
1     telephone   may         fri  ...         4    999         0   
2     telephone   jun         wed  ...         1    999         0   
3     telephone   jun         fri  ...         3    999         0   
4      cellular   nov         mon  ...         1    999         0   
...         ...   ...         ...  ...       ...    ...       ...   
4114   cellular   jul         thu  ...         1    999         0   
4115  telephone   jul         fri  ...         1    999         0   
4116   cellular   may         mon  ...         2    999         1   
4117   cellular   aug         fri  ...         1    999         0   
4118   cellular   nov         wed  ...         1    999         0   

         poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0     nonexistent         -1.8          92.893          -46.2      1.313   
1     nonexistent          1.1          93.994          -36.4      4.855   
2     nonexistent          1.4          94.465          -41.8      4.962   
3     nonexistent          1.4          94.465          -41.8      4.959   
4     nonexistent         -0.1          93.200          -42.0      4.191   
...           ...          ...             ...            ...        ...   
4114  nonexistent          1.4          93.918          -42.7      4.958   
4115  nonexistent          1.4          93.918          -42.7      4.959   
4116      failure         -1.8          92.893          -46.2      1.354   
4117  nonexistent          1.4          93.444          -36.1      4.966   
4118  nonexistent         -0.1          93.200          -42.0      4.120   

      nr.employed   y  
0          5099.1  no  
1          5191.0  no  
2          5228.1  no  
3          5228.1  no  
4          5195.8  no  
...           ...  ..  
4114       5228.1  no  
4115       5228.1  no  
4116       5099.1  no  
4117       5228.1  no  
4118       5195.8  no  

[4119 rows x 21 columns]

In [4]:
how_to_handle_columns = [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1]
for i, j in enumerate(input_df.columns):
    if (how_to_handle_columns[i] == 0):
        print('{}. {} : {} -> {}\n{}\n\n'.format(i, j, len(set(input_df[j])), '正則化', set(input_df[j])))
    else:
        print('{}. {} : {} -> {}\n{}\n\n'.format(i, j, len(set(input_df[j])), 'One-Hot', set(input_df[j])))
    

0. age : 67 -> 正則化
{18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 80, 81, 82, 85, 86, 88}


1. job : 12 -> One-Hot
{'technician', 'management', 'services', 'admin.', 'unemployed', 'entrepreneur', 'housemaid', 'unknown', 'blue-collar', 'self-employed', 'student', 'retired'}


2. marital : 4 -> One-Hot
{'divorced', 'single', 'married', 'unknown'}


3. education : 8 -> One-Hot
{'high.school', 'basic.4y', 'unknown', 'illiterate', 'basic.6y', 'university.degree', 'professional.course', 'basic.9y'}


4. default : 3 -> One-Hot
{'yes', 'unknown', 'no'}


5. housing : 3 -> One-Hot
{'yes', 'unknown', 'no'}


6. loan : 3 -> One-Hot
{'yes', 'unknown', 'no'}


7. contact : 2 -> One-Hot
{'telephone', 'cellular'}


8. month : 10 -> One-Hot
{'oct', 'may', 'apr', 'aug', 'dec', 'sep', 'nov', 'jul', 'jun', 'ma

In [5]:
input_df['job'][0]

'blue-collar'

In [6]:
# 建立one-hot用的dictionary
one_hot_dict = dict()
for i in input_df.columns:
    one_hot_dict[i] = list(set(input_df[i]))
# 先將要one-hot的欄位改成數字
input_df_one_hot = input_df.copy()
for i in input_df_one_hot.columns:
    if i == 'job' or i == 'marital' or i == 'education' or i == 'default' or i == 'housing' or i == 'loan' or i == 'contact' or i == 'month' or i == 'day_of_week' or i == 'pdays' or i =='previous' or i == 'poutcome' or i == 'y':
        for j in range(len(input_df_one_hot[i])):
            input_df_one_hot[i][j] = one_hot_dict[i].index(input_df_one_hot[i][j])
        #input_df_one_hot.rename(columns={i:i + '_one-hot'}, inplace = True)

C:\Users\User\AppData\Local\Temp/ipykernel_14316/3018114939.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_df_one_hot[i][j] = one_hot_dict[i].index(input_df_one_hot[i][j])


In [7]:
input_df_one_hot

age job marital education default housing loan contact month  \
0      30   8       2         7       2       0    2       1     1   
1      39   2       1         0       2       2    2       0     1   
2      25   2       2         0       2       0    2       0     8   
3      38   2       2         7       2       1    1       0     8   
4      47   3       2         5       2       0    2       1     6   
...   ...  ..     ...       ...     ...     ...  ...     ...   ...   
4114   30   3       2         4       2       0    0       1     7   
4115   39   3       2         0       2       0    2       0     7   
4116   27  10       1         0       2       2    2       1     1   
4117   58   3       2         0       2       2    2       1     3   
4118   34   1       1         0       2       0    2       1     6   

     day_of_week  ...  campaign  pdays  previous  poutcome emp.var.rate  \
0              2  ...         2     20         0         2         -1.8   
1              2  ...         4     20         0         2          1.1   
2              4  ...         1     20         0         2          1.4   
3              2  ...         3     20         0         2          1.4   
4              0  ...         1     20         0         2         -0.1   
...          ...  ...       ...    ...       ...       ...          ...   
4114           1  ...         1     20         0         2          1.4   
4115           2  ...         1     20         0         2          1.4   
4116           0  ...         2     20         1         1         -1.8   
4117           2  ...         1     20         0         2          1.4   
4118           4  ...         1     20         0         2         -0.1   

      cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0             92.893          -46.2      1.313       5099.1  1  
1             93.994          -36.4      4.855       5191.0  1  
2             94.465          -41.8      4.962       5228.1  1  
3             94.465          -41.8      4.959       5228.1  1  
4             93.200          -42.0      4.191       5195.8  1  
...              ...            ...        ...          ... ..  
4114          93.918          -42.7      4.958       5228.1  1  
4115          93.918          -42.7      4.959       5228.1  1  
4116          92.893          -46.2      1.354       5099.1  1  
4117          93.444          -36.1      4.966       5228.1  1  
4118          93.200          -42.0      4.120       5195.8  1  

[4119 rows x 21 columns]

In [8]:
# one hot 處理函式
def one_hot_encoding(input_number, category_size = 10):
    temp = np.zeros(category_size)
    temp[int(input_number)] = 1
    return temp

# 正規化處理函式
def normalize(input_number, max_, min_):
    return np.array((input_number - min_) / (max_ - min_))

In [9]:
input_df_one_hot[0:1]
input_df_one_hot[0:1]['age']+1
input_df_one_hot['age'].mean()
one_hot_dict['job']
one_hot_dict['y']
input_df_one_hot.index

RangeIndex(start=0, stop=4119, step=1)

In [21]:
X = list()
Y = list()
for j in range(input_df_one_hot.index.stop):
    df = input_df_one_hot[j:j+1]
    x = list()
    #x.append(np.array(normalize(df['age'], input_df_one_hot['age'].max(), input_df_one_hot['age'].min())))
    for i in input_df_one_hot.columns:
        if i == 'y':
            Y.append(one_hot_encoding(df[i], len(one_hot_dict[i])))
        elif i == 'job' or i == 'marital' or i == 'education' or i == 'default' or i == 'housing' or i == 'loan' or i == 'contact' or i == 'month' or i == 'day_of_week' or i == 'pdays' or i =='previous' or i == 'poutcome':
            x.append(one_hot_encoding(df[i], len(one_hot_dict[i])))
        else:
            x.append(normalize(df[i], input_df_one_hot[i].max(), input_df_one_hot[i].min()))
    X.append(x)

In [22]:
len(X), len(Y)
type(X[0][2])
len(X[0])

20

In [23]:
# 將list中的陣列串接
from tqdm import trange
for i in trange(len(X)):
    temp_x = X[i][0]
    for j in range(1, len(X[i])):
        temp_x = np.concatenate((temp_x, X[i][j]), axis=None)
    X[i] = temp_x
    del temp_x

100%|███████████████████████████████████████████████████████████████████████████| 4119/4119 [00:00<00:00, 23153.82it/s]


In [ ]:
# 切割成train, test, validation


In [40]:
def relu(input_array):
    for i in range(len(input_array)):
        if input_array[i]< 0:
            input_array[i] = 0
    return input_array

In [41]:
test = [-1, 2, 0, 3, -5]
relu(test)

[0, 2, 0, 3, 0]

In [50]:
def softmax(input_array):
    return np.exp(input_array)/sum(np.exp(input_array))
def softmax_2(input_array):
    input_array = input_array - input_array.max()
    return np.exp(input_array)/sum(np.exp(input_array))

In [52]:
test = np.array([-1, 2, 0, 3, -5])
print(softmax(test))
print(sum(softmax(test)))
print(softmax_2(test))
print(sum(softmax_2(test)))

[1.27518028e-02 2.56126805e-01 3.46629937e-02 6.96224841e-01
 2.33557415e-04]
1.0
[1.27518028e-02 2.56126805e-01 3.46629937e-02 6.96224841e-01
 2.33557415e-04]
1.0


In [67]:
def differential_relu(input_array):
    for i in range(len(input_array)):
        if input_array[i]<= 0:
            input_array[i] = 0
        else:
            input_array[i] = 1
    return input_array

In [68]:
test = np.array([-1, 2, 0, 3, -5])
differential_relu(test)

array([0, 1, 0, 1, 0])

In [28]:
class dense_layer:
    
    def __init__(self, units=40, input_shape=20, activation="relu"):
        super(dense_layer, self).__init__()
        self.units = units
        self.weight = np.reshape(np.random.uniform(0, 1, units*input_shape), (units, input_shape))
        self.bias = np.random.uniform(0, 1, units)
        self.activation = activation
        self.result = np.zeros(units)

In [60]:
class my_model:
    
    def __init__(self, input_units=20, units_of_hidden_layer=[40], activation_of_hidden_layer=["relu"], output_units=10):
        # 檢查隱藏層的參數數量有沒有一致
        if len(units_of_hidden_layer) != len(activation_of_hidden_layer):
            raise BaseException("Hidden Layer Parameter not match!")
            
        super(my_model, self).__init__()
        self.length_of_model = len(units_of_hidden_layer)
        self.layer_list = list()
        
        # create first hidden layer
        self.layer_list.append(dense_layer(units_of_hidden_layer[0], input_units, activation_of_hidden_layer[0]))
        
        # create the rest hidden layer
        for i in range(1, self.length_of_model):
            self.layer_list.append(dense_layer(units_of_hidden_layer[i], units_of_hidden_layer[i-1], activation_of_hidden_layer[i]))
            
        # create output layer
        self.layer_list.append(dense_layer(output_units, units_of_hidden_layer[-1], activation="softmax"))
        
    def feed_forward(self, x, y): #calculate and save the parameter for backpropagation later
        if self.layer_list[0].activation == 'relu': # need more activation function
            result = relu(self.layer_list[0].weight.dot(x.T) + self.layer_list[0].bias)
        for layer_index in range(1, len(self.layer_list)):
            if self.layer_list[layer_index].activation == 'relu':
                result = relu(self.layer_list[layer_index].weight.dot(result) + self.layer_list[layer_index].bias)
        if self.layer_list[-1].activation == 'softmax':
            result = softmax_2(self.layer_list[-1].weight.dot(result) + self.layer_list[-1].bias)
        print(result)
        
#     def train(self, train_x, train_y, batch_size, epochs):
#         for _ in range(epochs):
#             #shuffle before each epoch
#             from random import shuffle
#             random.shuffle(train_x)
#             for batch_index in range(0, epoch/batch_size, batch_size):
#                 # main feed_forward
#                 for batch_sub_index in range(batch_size):
#                     for layer in layer_list:
                        
        

In [63]:
test = my_model(input_units=89, units_of_hidden_layer=[40], activation_of_hidden_layer=["relu"], output_units=10)
print(test.length_of_model)
# print(test.layer_list[0].weight.shape)
for i in test.layer_list:
    print(i.weight)
temp_x = np.ones((89))
temp_y = np.random.random((100))
test.feed_forward(temp_x, temp_y)

1
[[0.80705112 0.35883955 0.07387547 ... 0.08078655 0.35592711 0.39903327]
 [0.8526505  0.16878486 0.57526296 ... 0.43499948 0.38890092 0.36579447]
 [0.27736229 0.36746962 0.61398986 ... 0.49239367 0.18904904 0.60025717]
 ...
 [0.79022741 0.97447254 0.12202123 ... 0.17165056 0.00208543 0.98600853]
 [0.29917415 0.36823583 0.85729549 ... 0.35881744 0.1570419  0.99360079]
 [0.6843654  0.59514205 0.11588602 ... 0.62174158 0.14977364 0.13622342]]
[[0.34367365 0.71323857 0.80032875 0.7175568  0.40710645 0.75608717
  0.51274715 0.9243702  0.32011956 0.66149319 0.99916181 0.8386072
  0.18251715 0.52524978 0.02999741 0.90672038 0.27572297 0.61341254
  0.50567133 0.26900067 0.54350442 0.96932135 0.73446578 0.86134967
  0.87917644 0.0285373  0.57428687 0.01780507 0.28166361 0.02246069
  0.53862925 0.73990341 0.54999318 0.82220599 0.52075642 0.21355415
  0.26040194 0.63111104 0.27467471 0.61869703]
 [0.19077995 0.81102107 0.54893691 0.13410384 0.17640895 0.03605835
  0.19675415 0.0094478  0.168669